### ISSUE TITLE
Play games by using in-screen controller for mobile gaming

### ISSUE THREAD

**Issue by tintheanh** [andychase/gbajs2#14] opened 2020-09-07 17:41 UTC
Suggest having in-screen controller using <button> for playing on mobile. We can create a new class to handle <button> controls just like keypad.js

**Comment by andychase** [comment] 2020-09-08 03:18
Good idea! Might be the same as #7

**Comment by jriceart** [comment] 2020-09-11 12:09
@tintheanh I've posted the GBA designs with on screen controller on a different issue board,  didn't know if you saw these yet

https://www.figma.com/file/azIaf5sIOT1Vj86lIui0El/GBA.js?node-id=0%3A1

**Comment by tintheanh** [comment] 2020-09-11 18:37
@jriceart The UI looks great! If the front-end code is not yet implemented I can try to jump in and work on it.

**Comment by andychase** [comment] 2020-09-15 19:05
Duplicate of #13

**Closed by andychase** 2020-09-15 19:05 UTC
